name: hello

on: [push]

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: Run a one-line script
          run: echo Hello, world!
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
  job2:
    name: second job
    runs-on: windows-latest

    steps:
        - uses: actions/checkout@v1
        - name: Run a one-line script
          run: echo Hello, world!
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
  job3:
        needs: [job1, job2]
        name: Thjird job
        runs-on: macos-latest
        steps:
            - run: date
